---
version: '3'

volumes:
  data-murmur: {}

services:
  murmur:
    image:  no42org/murmur:1.3.1.1168
    container_name: murmur
    volumes: 
      - ./murmur.ini:/opt/murmur/murmur.ini
      - data-murmur:/data
    ports:
      - "64738:64738/tcp"
      - "64738:64738/udp"
    command: [ "-fg", "-ini", "./murmur.ini" ]
