---
version: '3'

services:
  bzfs:
    image: no42org/bzflag-server:2.4.18.20200324.1204
    container_name: bzfs
    network_mode: host
    volumes:
      - ./conf.txt:/conf.txt
    command: [ "-conf", "/conf.txt"]
